# Generated by Django 3.2.7 on 2021-09-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='roll_num',
        ),
    ]
